/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JVorbisFile */

#ifndef _Included_JVorbisFile
#define _Included_JVorbisFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JVorbisFile
 * Method:    jvorbOpen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JVorbisFile_jvorbOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JVorbisFile
 * Method:    jvorbRead
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_JVorbisFile_jvorbRead
  (JNIEnv *, jobject, jobject);

/*
 * Class:     JVorbisFile
 * Method:    jvorbClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JVorbisFile_jvorbClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
